FROM condaforge/mambaforge:4.11.0-4

ENV CONDA_CACHE_DIR=/opt/conda/pkgs
ENV PIP_CACHE_DIR=/opt/pip/.cache
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt update && apt install -y \
    # build tooling
    ccache cmake make build-essential \
    # required for openmpi in horovod, we don't really use ssh functionality
    openssh-client openssh-server





