FROM condaforge/mambaforge:4.11.0-4

ENV CONDA_CACHE_DIR=/opt/conda/pkgs
ENV PIP_CACHE_DIR=/opt/pip/.cache
ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apt update && apt install -y \
    # build tooling
    ccache cmake make build-essential \
    # required for openmpi in horovod, we don't really use ssh functionality
    openssh-client openssh-server

COPY environment.yml .
RUN --mount=type=cache,target=$CONDA_CACHE_DIR --mount=type=cache,target=$PIP_CACHE_DIR mamba env create -f environment.yml

RUN echo "conda activate dbx_scalable_dl" >> ~/.bashrc
SHELL ["/bin/bash", "--login", "-c"]

ENV PATH="/opt/conda/envs/dbx_scalable_dl/bin:$PATH"

RUN --mount=type=cache,target=$PIP_CACHE_DIR pip install tensorflow-cpu==2.8.0 keras==2.8.0
RUN --mount=type=cache,target=$PIP_CACHE_DIR HOROVOD_WITH_TENSORFLOW=1 pip install "horovod[tensorflow,spark]==0.24.0"

ADD . .

RUN --mount=type=cache,target=$PIP_CACHE_DIR pip install -e .



