name: dbx_scalable_dl

channels:
  - conda-forge
  - defaults

dependencies:
  # environment deps
  - python=3.8.10
  - openjdk=8.0.152
  - pip
  - fftw
  - libopenblas
  - libxml2
  - cxx-compiler
  - mkl-include
  - mkl
  - cffi
  - openmpi
  - mpi4py
  - numpy
  - libclang
  # dev-related dependencies
  - pytest
  - setuptools
  - wheel
  - pyyaml
  - pytest
  - pytest-cov
  - black
  - pip:
      # dev-related
      - dbx
      - pytest-httpserver
      # env-related dependencies
      - pyspark==3.1.2
      - delta-spark==1.0.1
      - petastorm==0.11.2
      - tensorflow==2.8.0