custom:
  basic-cpu-cluster-props: &basic-cpu-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-gpu-cluster-props: &basic-gpu-cluster-props
    spark_version: "10.4.x-gpu-ml-scala2.12"

  cluster-log-conf: &cluster-log-conf
    cluster_log_conf:
      dbfs:
        destination: "dbfs:/cluster-logs"

  model-builder-compute-conf: &model-builder-compute-conf
    instance_pool_name: scalable-dl-pool
    driver_instance_pool_name: scalable-dl-pool

  single-node-conf: &single-node-conf
    num_workers: 0
    spark_conf:
      "spark.databricks.cluster.profile": "singleNode"
      "spark.master": "local[*, 4]"
    custom_tags:
      "ResourceClass": "SingleNode"

  data-loader-cluster: &data-loader-cluster
    new_cluster:
      <<: [ *basic-cpu-cluster-props ]
      num_workers: 2
      driver_node_type_id: "i3.xlarge"
      node_type_id: "i3.xlarge"
      aws_attributes:
        first_on_demand: 1

  model-builder-cluster-1x: &model-builder-cluster-1x
    new_cluster:
      <<: [ *basic-gpu-cluster-props, *cluster-log-conf, *model-builder-compute-conf, *single-node-conf ]



  model-builder-cluster-2x: &model-builder-cluster-2x
    new_cluster:
      <<: [ *basic-gpu-cluster-props, *cluster-log-conf, *model-builder-compute-conf ]
      num_workers: 2

  model-builder-cluster-4x: &model-builder-cluster-4x
    new_cluster:
      <<: [ *basic-gpu-cluster-props, *cluster-log-conf, *model-builder-compute-conf ]
      num_workers: 4

  model-builder-cluster-8x: &model-builder-cluster-8x
    new_cluster:
      <<: [ *basic-gpu-cluster-props, *cluster-log-conf, *model-builder-compute-conf ]
      num_workers: 8

  data-loader-launch: &data-loader-launch
    spark_python_task:
      python_file: "file://dbx_scalable_dl/tasks/data_loader.py"
      parameters: [ "--conf-file", "file:fuse://conf/params/data_loader.yml" ]

  model-builder-launch: &model-builder-launch
    spark_python_task:
      python_file: "file://dbx_scalable_dl/tasks/model_builder.py"
      parameters: [ "--conf-file", "file:fuse://conf/params/model_builder.yml" ]

# please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "dbx-scalable-dl-data-loader"
        <<: [ *data-loader-launch, *data-loader-cluster ]
      - name: "dbx-scalable-dl-model-builder-1x" # single node
        <<: [ *model-builder-launch, *model-builder-cluster-1x ]
      - name: "dbx-scalable-dl-model-builder-2x" # 2 workers
        <<: [ *model-builder-launch, *model-builder-cluster-2x ]
      - name: "dbx-scalable-dl-model-builder-4x" # 4 workers
        <<: [ *model-builder-launch, *model-builder-cluster-4x ]
      - name: "dbx-scalable-dl-model-builder-8x" # 8 workers
        <<: [ *model-builder-launch, *model-builder-cluster-8x ]

