custom:
  basic-cpu-cluster-props: &basic-cpu-cluster-props
    spark_version: "10.4.x-cpu-ml-scala2.12"

  basic-gpu-cluster-props: &basic-gpu-cluster-props
    spark_version: "10.4.x-gpu-ml-scala2.12"

  data-loader-cluster: &data-loader-cluster
    new_cluster:
      <<: [ *basic-cpu-cluster-props ]
      num_workers: 2
      driver_node_type_id: "i3.xlarge"
      node_type_id: "i3.xlarge"
      aws_attributes:
        first_on_demand: 1


  model-builder-cluster-single-node: &model-builder-cluster-single-node
    new_cluster:
      <<: [ *basic-gpu-cluster-props ]
      driver_node_type_id: "p3.2xlarge"
      node_type_id: "p3.2xlarge"
      num_workers: 0
      spark_conf:
        "spark.databricks.cluster.profile": "singleNode"
        "spark.master": "local[*, 4]"
      custom_tags:
        "ResourceClass": "SingleNode"
      aws_attributes:
        ebs_volume_count: 1
        ebs_volume_size: 32

  model-builder-cluster-multi-node: &model-builder-cluster-multi-node
    new_cluster:
      <<: [ *basic-gpu-cluster-props ]
      driver_node_type_id: "g5.xlarge" # we choose the smallest and cheapest GPU since driver resources won't be used
      node_type_id: "p3.2xlarge"
      num_workers: 4
      aws_attributes:
        ebs_volume_count: 1
        ebs_volume_size: 32

  data-loader-launch: &data-loader-launch
    spark_python_task:
      python_file: "file://dbx_scalable_dl/tasks/data_loader.py"
      parameters: [ "--conf-file", "file:fuse://conf/params/data_loader.yml" ]

  model-builder-launch-sn: &model-builder-launch-sn
    spark_python_task:
      python_file: "file://dbx_scalable_dl/tasks/model_builder.py"
      parameters: [ "--conf-file", "file:fuse://conf/params/model_builder_sn.yml" ]

  model-builder-launch-mn: &model-builder-launch-mn
    spark_python_task:
      python_file: "file://dbx_scalable_dl/tasks/model_builder.py"
      parameters: [ "--conf-file", "file:fuse://conf/params/model_builder_mn.yml" ]

# please note that we're using FUSE reference for config file, hence we're going to load this file using its local FS path
environments:
  default:
    strict_path_adjustment_policy: true
    jobs:
      - name: "dbx-scalable-dl-data-loader"
        <<: [ *data-loader-launch, *data-loader-cluster ]
      - name: "dbx-scalable-dl-model-builder-sn" # sn = single node
        <<: [ *model-builder-launch-sn, *model-builder-cluster-single-node ]
      - name: "dbx-scalable-dl-model-builder-mn" # mn = multi node
        <<: [ *model-builder-launch-mn, *model-builder-cluster-multi-node ]


