FROM nocturne-base

ENV PIP_CACHE_DIR=/opt/pip/.cache


WORKDIR /usr/src/project

COPY dev-requirements.txt .
RUN --mount=type=cache,target=$PIP_CACHE_DIR pip install -r dev-requirements.txt

COPY . .

RUN pip install -e .