FROM renardeinside/nocturne-base

ENV POETRY_CACHE_DIR=/root/.cache/pypoetry


WORKDIR /usr/src/project

COPY .. .

RUN --mount=type=cache,target=$POETRY_CACHE_DIR poetry config virtualenvs.create false && poetry install -n


