batch_size: 32768
database: "dbx_scalable_dl_demo"
table: "ratings"
cache_dir: "file:///dbfs/tmp/petastorm/cache"
num_epochs: 10
model_name: "dbx_scalable_dl_demo"
dataset_size_limit: 200000
mlflow:
  experiment: "/Shared/dbx_scalable_dl_demo"
metric_collection:
  request_interval: 20 # in seconds
  database: "dbx_scalable_dl_demo"
  table: "metrics"