name: CI pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  ci-pipeline:

    runs-on: ubuntu-latest

    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
      DOCKER_BUILDKIT: 1

    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: set up docker registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin

      - name: pull cached image
        run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/dbx_scalable_dl || true # true switch for case when there is no image to pull

      - name: build test image
        run: docker build -t dbx_scalable_dl --file=Dockerfile.dev . --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/dbx_scalable_dl

      - name: run tests
        run: make test

      - name: push the test image
        run: |
          docker tag dbx_scalable_dl docker.pkg.github.com/$GITHUB_REPOSITORY/dbx_scalable_dl
          docker push docker.pkg.github.com/$GITHUB_REPOSITORY/dbx_scalable_dl



